### PR TITLE
Implement TAG_Long_Array

### PR DESCRIPTION
**Pull request by flori-schwa**
As described here: [https://wiki.vg/NBT#Specification](https://wiki.vg/NBT#Specification)

### CODE REVIEW

**Comment by eouw0o83hf** [comment]
Definitely need this to parse modern NBT files, @mstefarov possibility of merging so the nuget package is updated?

**Comment by Origon** [comment]
I would really like this to be added into the NuGet package as well.

**Review by mstefarov — APPROVED** [review]
Thank you for contributing this! I apologize for a very long delay in reviewing this PR. I'll try to get this out in a proper release soon.

**Comment by Equbuxu** [comment]
Can't wait for the NuGet package update

**Pull request merged**
